"""Add profile_picture to User model

Revision ID: 81361463ba1e
Revises: 
Create Date: 2025-05-16 21:41:49.751596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81361463ba1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###
