"""Criando tabelas de usuários

Revision ID: 92856f0ab618
Revises: 0fa2148c01ad
Create Date: 2025-05-20 15:35:38.813077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92856f0ab618'
down_revision = '0fa2148c01ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
